---
- name: install versions
  shell: bash -lc "nvm install {{ item }}"
  register: output
  changed_when: "'already installed.' not in output.stderr"
  with_items: "{{ boss__nvm_node_versions }}"

- name: create alias directory
  file: path="{{ boss__nvm_root }}/alias" state=directory

- name: set {{ boss__nvm_default_node_version }} as default version
  copy: dest="{{ boss__nvm_root }}/alias/default" content="{{ boss__nvm_default_node_version }}"
