---
- name: install packages for each user
  shell: bash -lc "nvm use {{ item.1 }} && npm install -g {{ item.2 }}"
  become: true
  become_user: "{{ item.0 }}"
  with_nested:
    - "{{ boss__nvm_users }}"
    - "{{ boss__nvm_node_versions }}"
    - "{{ boss__nvm_global_packages }}"
